### ISSUE TITLE
Ironberry Juice & Drying Basin - Rustic vs Cuisine

### ISSUE THREAD

**Issue by Aesuth** [thephoenixlodge/Heavens-of-Sorcery#113]
There are some circumstances (currently unable to pinpoint specific circumstances) that cause ironberry juice in a rustic crushing tub to come out as a tagged version of `<liquid:cuisine_juice>` from Cuisine instead of `<liquid:ironberryjuice>` from Rustic.

This bit of ZScript should fix this inline with the normal Rustic recipe for evaporating Ironberry Juice : 

```
mods.rustic.EvaporatingBasin.addRecipe(
    <rustic:dust_tiny_iron> * 1,
    <liquid:cuisine_juice>.withTag({material: "ironberry"}) * 500
);
```

**Comment by thephoenixlodge** [comment]
Tried your fix, but had to revert, as it allows ANY cuisine juice to work. For now, this is an unavoidable weirdness caused by Cuisine being dumb and using NBT tags on fluids...

At any rate, the only time you'll get the cuisine juice is if you but the berries in the cuisine tub, So just don't do that.
