### ISSUE TITLE
Advancements for mods

### ISSUE THREAD

**Issue by Jomeaga** [thephoenixlodge/Heavens-of-Sorcery#23]
The advancements for specific mods seem to be disabled, only the modpack quest advancements show up. Could the mod specific ones be re-enabled?

Some mods like Misty world have awful documentation, and rely on the advancements to guide the player.

**Comment by thephoenixlodge** [comment]
Many of these are inherently broken due to recipe tweaks - advancements look at recipe ids, and any changes to recipes result in new ids. While it is possible to re-implement the mods advancements and manually fix all the broken ones, I don't believe it is worth the effort, as with most mods they're just for fun, and don't give much actual information.
In the case of Misty World, a majority of what is covered in its advancements is already documented more thoroughly in the pack's quest book. If there's a specific bit of it you have in mind that needs documenting, let me know and it can be added to the book.

**Comment by Jomeaga** [comment]
- How to get saplings, because you can't just break the leaves or cut down the tree; you have to break the branches that directly support leaves to get a small chance

- Quick explanation that each island is it's own biome, and which biomes the detox items/rustic things spawn in (beehives only spawn in jungles and you need them for soap)

- How to use the Misty world rubber trees
